config/routes.rb
Rails.application.routes.draw do
  
 
  
  devise_for :users
 

  resources :posts
  get '/main/place'
  get '/main/back'
  root 'main#index'
  get '/main/search'
  get '/main/do'
  get '/main/my'
  get '/main/my_page'
  post '/create' => 'main#create'
  get '/main/pick'
  get '/main/test'
  get '/main/back_event'

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/place.rb
class Place < ActiveRecord::Base
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
   

    mount_uploader :image, S3Uploader
end

app/models/user.rb
class User < ActiveRecord::Base
 
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:age,:gender])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:age,:gender])

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def yang
  end
  
  def place
    
    @p = Place.new
    @p.content = params[:place]
    @p.save
    redirect_to '/'
  end
  
  
  def back
    redirect_to :back
  end
 
  def pick
    @pi = Pick.new
    @pi.post_id_id = params[:post_id]
    @pi.user_id_id = current_user.id
    @pi.save
    
    redirect_to '/'

  end
  
  def search
    @all = Post.all
    #pagination
    # @all = Post.page params[:page]
    # 검색 기능
    @search = Post.where('location LIKE :search',search: "%#{params[:place_search]}%").first
    @search_all = Post.where('location LIKE :search',search: "%#{params[:place_search]}%")
    # @search_all = Post.page params[:page]
    
    @something = params[:place_search]
  end
  
  def create
    Post.create(title: params[:title], content: params[:content], image: params[:image])
    redirect_to :back
  end
  
  def test
    @all = Post.all
  end
  
  def my_page
    @mypost = Post.where(:user_id => current_user.id)
    @pick = Pick.where(:user_id_id => current_user.id)
    @user = User.where(:id => current_user.id)
    
   
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end

        
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new
    @post.title = params[:title]
    @post.ty = params[:type]
    @post.location = params[:location]
    @post.lat = params[:lat]
    @post.lng = params[:lng]
    @post.content = params[:content]
    @post.tel = params[:tel]
    @post.money = params[:money]
    @post.sday = params[:sday]
    @post.eday = params[:eday]
    @post.image = params[:image2]
    
    @post.f_wifi = params[:f_wifi]
    @post.f_shower = params[:f_shower]
    @post.f_parking = params[:f_parking]
    @post.f_clothes = params[:f_clothes]
    @post.f_rocker = params[:f_rocker]
    @post.user_id = current_user.id
    @post.save
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
    :user
    end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>  
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <div class="field form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  
  <div class="field form-group">
    <%= submit_tag "댓글 작성", style: "float: right" %><br/>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>  
  <div class="comments-show">
    <div class="comment">
      <%= comment.user != nil ? comment.user.email : comment.email %> / <%= time_ago_in_words(comment.created_at) %>전 [ <%= comment.created_at.strftime('%Y-%m-%d %H:%M') %> ] /
      <%= link_to "지우기", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "color: red; font-weight: bold" %>
      <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %>
      
      <div class="comment-nav" align="right">
        <a onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()">답댓글</a>
      </div>
      
      <div id="comment_<%= comment.id %>" style="display:none;">
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <div class="field form-group">
              <%= f.hidden_field :nickname, value: current_user.email, required: "true" %>
              <%= f.text_area :body, class: 'form-control' %>
            </div>
            <div class="field form-group">
              <%= submit_tag "답댓글 작성", style: "float: right;" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div style="margin-left: 100px;">
      <%= render partial: "comments/reply_end", locals: {comments: comment.children} %>
    </div>
  </div>
  <hr/>
<% end %>

app/views/comments/_template.html.erb
<div class="comments-header">  
    <h4>댓글 (<%= commentable.comment_threads.count %>)</h4>
</div>
 
<div class="comments-container">  
    <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>
<hr/>
<%= render partial: "comments/form", locals: {new_comment: new_comment} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Baton Touch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/main.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
  <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="/app/assets/stylesheets/agency.min.css" rel="stylesheet">
    
    <link rel="stylesheet" type="text/css" href="/assets/stylesheets/slick.css"/>
   <link rel="stylesheet" type="text/css" href="/assets/stylesheets/slick-theme.css"/>
<script type="text/javascript">
    function showHide(id) {
       var obj = document.getElementById(id);
       if (obj.style.display == 'none')
           obj.style.display = 'block';
       else
           obj.style.display = 'none';
    }
</script>



</head>
<body>
 

<style>
  @media (max-width:992px){
    .container{
      max-width:100%;
      
    }
    .col-sm-12{
      flex: 0 0 100%;
      width:100%;
    }
    #aaa{
      
      max-width:100%;
      height:auto;
      width:150px;
      margin-bottom:50px;
    }
    #bbb{
      width: 100%;
      height:auto; 
      max-width:100%;
    }
    #imim{
      width:40%;
    }
  }
   @media (min-width:993px){
     
   
    #ccc {
        text-align: center;
    }
    #ddd {
        text-align: left;
        padding-right: 200px;
    }
   #imim{
     width:200px;
     margin-left: 35px;
   }
    #aaa {
      padding: 30px;
        text-align: center;

    }
    #bbb {
        text-align: left;
        
    }
     
   }
</style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color: #000000; ">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/"><img src="/assets/logogo.png" style="width:200px;"></a>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/main/my_page">마이페이지</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/users/sign_out" data-method="delete">로그아웃</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/posts/new">양도권 업로드</a>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#" data-toggle="modal" data-target="#exampleModal">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/users/sign_up" >회원가입</a>
            </li>
            
            <% end %>
            
            
          </ul>
        </div>
      </div>
    </nav>
    
    
<%= yield %>
<br><br>

<style>
      
</style>


<footer >

  <div class="container">
    <a href="#"><i class="angle double up icon"></i></a>
    <div class="ui centered grid" style="margin-bottom: 50px;">
      <div class="eight wide column" id="ccc">
        
        <br><br><br>
        <p><strong>주소</strong> 17104 경기도 용인시 기흥구 덕영대로 1732 </p>
        <p><strong>custom center</strong> 010-1234-5678 </p>
        <p><strong>email</strong> abc123@naver.com </p>
        <p>Copyright ⓒ 2018 Likelion 6  Designed by Baton Touch </p>
        
      </div>
      <center>
      <div class="eight wide column" id="ddd">
        <br><br>
        <p><strong>president</strong> 이동훈</p>
        <P><strong>designer</strong> 정유진</P>
        <P><strong>designer</strong> 이진희</P>
        <P><strong>developer</strong> 민태원</P>
        <P><strong>developer</strong> 엄지현</P>
  
      </div>
      </center>
    </div>
  </div>

    
    </footer>
    
    
<!-- 로그인 모달창 -->
<div class="modal fade" style="z-index: 3000;" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <!--여기에 로그인 페이지 붙여넣기-->
        <div class="ui centered grid" style="margin: 2% 0 0 2%;">
          <div class="col-xs-12 col-sm-12  col-md-6" id="aaa">
            <img id="imim" src="/assets/batontouch_yellow.png"/>
          </div>
          
          <div class="col-xs-12 col-sm-12 col-md-6" id="bbb" >
        
        <div class="ui basic padded segment">
          
        <!--오류나는곳-->
          <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:class => 'ui small form'}) do |f| %>
  <div class="field">
    <div class="ui fluid left icon input" >
      <i class="envelope icon"></i>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "E-mail address" %>
    </div>
  </div>

  <div class="field">
    <div class="ui fluid left icon input">
      <i class="key icon"></i>
      <%= f.password_field :password, autocomplete: "off", placeholder: "Password"%>
    </div>
  </div>
  
  <div class="field">
      <%= f.submit '로그인', :class => "ui fluid yellow button" %>
  </div>
  
  <div class="field">
  <button type="button" onclick="location.href= '/users/sign_up' " class="ui fluid yellow button">회원가입</button>
    <!-- <div id="signup_popup" class="ui fluid yellow button" data-toggle="modal" data-target="#modalsignup">회원가입</div> -->
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <div class="ui toggle checkbox">
        <%= f.check_box :remember_me %>
        <label>비밀번호 저장</label>
      </div>
    </div>
  
    
  <% end -%>

<% end %>
<!--여기까지 수정-->

</div>
<!--회원가입 모달창-->
    <div class="modal fade2" style="z-index: 3000" id="modalsignup" tabindex="-1" role="dialog" aria-labelledby="modalsignupLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <!--여기에 회원가입 페이지 붙여넣기-->
  <center>
   <h2><img class="img_2" src ='/assets/little.png' width='150px'/></h2>
    </center><br>
 

    <center>
     <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {class: "ui large form"}) do |f| %>
  <%= f.error_notification %>

   <div class="ui input">
    <%= f.input :name,
                
                label: false,
                required: true,
                autofocus: true ,
                placeholder: "name",
                input_html: { class: 'ui input' }%>
                </div><br><br>
                
                <div class="ui input">
    <%= f.input :age,
                required: true,
                label: false,
                placeholder: "age",
                autofocus: true ,
                input_html: { class: "ui input"}%>
     </div><br><br>
     <div class="ui input">
    <%= f.input :gender, 
                as: :radio_buttons, 
                collection: [['여자', 'female'], ['남자', 'male']], 
                label_method: :second, 
                value_method: :first,
                required: true,
                label: false,
                autofocus: true ,
                input_html: { class: "ui input" }%>
                   </div><br><br>
            <div class="ui input">    
    <%= f.input :email,
                required: true,
                label: false,
                placeholder: "email",
                autofocus: true ,
                input_html: { class: "ui input" }%>
                   </div><br><br>
                <div class="ui input">
    <%= f.input :password,
                required: true,
                label: false,
                placeholder: "password(more than 6)",
                input_html: {class: "ui input" } %>
                   </div><br><br>
                <div class="ui input">
    <%= f.input :password_confirmation,
                required: true,
                label: false,
                placeholder: "password_confirmation",
                input_html: { class: "ui input" } %>
                   </div><br><br>
 

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<!--회원가입 모달창 끝 -->



        </div>
        
        <%if false%>
        <%= render "devise/shared/links" %>
        <%end%>
        
        
          </div>
              </div>
        </div>
          
      </div>
    </div>
  </div>
</div>


    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Plugin JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <!-- Custom scripts for this template -->
    <script src="/assets/agency.min.js"></script>
    
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/assets/slick.min.js"></script>
    
    
  <br><br>
  <hr><br>
  
</body>
</html>

app/views/main/my.html.erb
<!DOCTYPE html>

<html lang="ko">

<head>

    <meta charset="UTF-8" />

    <title>slick test</title>

   
				

    

</head>

<body>

    <div class="slick-items">

        <div>111</div>

		<div>222</div>

		<div>333</div>

		<div>444</div>

		<div>555</div>

    </div>

</body>





<script type="text/javascript">



$(document).ready(function () {

	//alert('123');

	$('.slick-items').slick({

		autoplay : true,

		dots: true,

		speed : 300 /* 이미지가 슬라이딩시 걸리는 시간 */,

		infinite: true,

		autoplaySpeed: 3000 /* 이미지가 다른 이미지로 넘어 갈때의 텀 */,

		arrows: true,

		slidesToShow: 1,

		slidesToScroll: 1,

		fade: false

	});

});



</script>

</html>

app/views/posts/edit.html.erb
  <style>
    .date-input {     
    width: 145px;
    padding-top: 0px;
}
        .search_category {
            margin-top: 100px;
            width: 100%;
            height: 70px;
            padding: 10px;
        }
        .search_detail {
            width: 100%;
            height: 750px;
        }
        #n_1 {
            border: 1px solid black;
        }
        #search_input {
            margin-left: 20px;
        }
        #segment_content {
            margin-left: 20px;
        }
        
         @media (max-width:992px){
             .tt{
                 margin-left:5%;
                 margin-right:5%;
             }
             .container{
                 max-width:100%;
                 width:100%;
                 margin-left:0;
                 margin-right:0;
             }
             
             #e1{
                 width:100%;
             }
         }
         
         @media (min-width:993px){
             .tt{
                 margin-left:15%;
                 margin-right:15%;
             }
             #e1{
                 position:relative; 
                 left:50px; bottom:25px;
             }
         }
    </style>
<br><br><br><br><br><br><br><br>
<%= render 'form2' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.erb
<style>

.tt .t1{
    font-size:17px;
    font-weight:bold;
}

.tt .t2{
    margin-left:5%;
}

@media (min-width:993px){
    
     #pic{
         width:65px;
         height:65px;
     }
     #hi{
         width:750px;
     }
     
     #c1{
      margin-top:105px;
  }
  td{
      padding:10px;
     
  }
 
 .col-md-6 img{
      float:left;
      
  }
  .col-md-6{
      margin-bottom:25px;
  }
  .col-md-6 p{
      
      padding-top:27px;
      height:100px;
      vertical-align:middle;
      padding-left:10%;
      float:left;
      font-size: 25px;
      font-weight: bold;
  }
 
} 
   @media (max-width:992px){
       .container{
           width:100%;
           
       }
     #c1{
        margin-top:69px;
        
    }
     #pic{
         width:30px;
         height:30px;
     }
     #hi{
         width:300px;
     }
     
 .col-md-6  p{
      padding-top:27px;
      height:100px;
      vertical-align:middle;
      
       font-size: 20px;
       font-weight: bold;
  }
  
 
} 
.col-md-6 img{
    width:75px;
    height:75px;
    
}


.col-xs-1{
    width:50%;
}
</style>

<center>
<div id="c1" class="container">
    <% if @post.image.present? %>
        <img id="hi" src="<%= @post.image.url %>" style="width:100% margin-up:100px;">
    <% end %>
</div>
</center>

<br><br>
<div class="container">
    <p style="font-size:25px; font-weight:bold; color:#FCCF54;padding-left:5%"><%= @post.ty %></p>
    <p style="font-size:50px;font-weight:bold;padding-left:5%"><%= @post.title %></p>
    <p style="font-size:18px; color:#848484;padding-left:5%"><%= @post.location %></p>
</div>
<br><br><br>
<div class="container" >
    <div class="tt" style="margin-left:10%;">
        <p class="t1">이용 기간</p>
        <p class="t2"><%= @post.sday %> ~ <%= @post.eday %></p>
        <p class="t1">양도 기간</p>
        <p class="t2"><%= @post.sday %> ~ <%= @post.eday %></p>
        <!--<p class="t1">원가</p>
        <p class="t2">1,000,000원</p> -->
        <p class="t1">판매가</p>
        <p class="t2"><%= @post.money %>원</p>
        

        <p class="t1">전화 번호</p>
        
        
        

                
        <p class="t2">
                <button class="ui basic button" onclick="document.location.href='<%= @post.tel %>'"> <a href="tel:<%= @post.tel %>"><%= @post.tel %> 로 전화걸기</a>  </button>
        </p>
        

        
        <p class="t1">편의시설</p>
        <div class="container" style="padding-left:5%">
        <div class="row" style="width:100%;">
            <% if @post.f_rocker == "on" %>
                <div class="col-xs-1 col-sm-6 col-md-6"><img id="pic" src="/assets/key.png"><p>보관 시설</p></div>
             <% end %>
              <% if @post.f_parking== "on" %>
                <div class="col-xs-1 col-sm-6 col-md-6"><img id="pic" src="/assets/parking.png"><p>주차 시설</p></div>
             <% end %>
              <% if @post.f_clothes == "on" %>
                <div class="col-xs-1 col-sm-6 col-md-6"><img id="pic" src="/assets/shirts.png"><p>운동복 대여</p></div>
             <% end %>
              <% if @post.f_shower == "on" %>
                <div class="col-xs-1 col-sm-6 col-md-6"><img id="pic" src="/assets/ta.png"><p>샤워 시설</p></div>
             <% end %>
              <% if @post.f_wifi== "on" %>
                <div class="col-xs-1 col-sm-6 col-md-6"><img id="pic" src="/assets/wifi.png"><p>무선 인터넷</p></div>
             <% end %>
          
        </div>
        </div>
      
    </div>
</div>

<center>
<div class="ui form" style="width:1000px; height:250px; padding: 50px;">
  <div class="field">
    <textarea style="font-size:17px; font-color:gray;"><%= @post.content %></textarea>
  </div></div></center>
    

<br><br>
<div class="container" style=" width:80%;">
    <h2>시설의 위치를 확인해 보세요</h2>
</div>
<br>
<div class="container">
    <% if @post.lat.present? %>
        <div id="map" style="height:400px; width:100%;"></div>
    <% else %>
        <h3 style="text-align:center;">위치 정보가 없습니다.</h3>
    <% end %>
</div>
<br><br>


<div class="container" style="text-align:center; margin-top:">
    <% if user_signed_in? %>
      <% if @post.user_id.to_i == current_user.id %>
       <div style="display:inline-block;"><button class="ui button"><%= link_to '수정', edit_post_path(@post) %></button></div>
      <% end %>
    <% end %>
    <div style="display:inline-block;">
        <button class="ui black button"><%= link_to '뒤로가기', :back %></button>
    </div>
    <div style="display:inline-block">
        <% if user_signed_in? %>
          <form action="/main/pick">
           <input type="hidden" name="post_id" value= <%= @post.id %> >
           <input type="submit" value="찜하기" class="ui yellow button">
          </form>
        <% end %>
    </div>
</div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=b5a7ee0065f76f4f7ae106a301a8fa9c&libraries=services"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new daum.maps.LatLng('<%= @post.lat %>', '<%= @post.lng %>'), // 지도의 중심좌표
        draggable: false,
        level: 3 // 지도의 확대 레벨
    };

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// 마커가 표시될 위치입니다 
var markerPosition  = new daum.maps.LatLng('<%= @post.lat %>', '<%= @post.lng %>'); 

// 마커를 생성합니다
var marker = new daum.maps.Marker({
    position: markerPosition
});

// 마커가 지도 위에 표시되도록 설정합니다
marker.setMap(map);

</script>
<!-- 

-->